export const POSITION_DATA = [
    { id: 1, name: 'Design Engineer Trainee', pkey: 'DET' },
    { id: 2, name: 'Design Engineer I', pkey: 'DE1' },
    { id: 3, name: 'Design Engineer II', pkey: 'DE2' },
    { id: 4, name: 'Design Engineer III', pkey: 'DE3' }
]

export const DEPARTMENT_DATA = [
    { id:1, name: 'VSBU' },
    { id:2, name: 'SSSBU' },
]

export const BUSINESS_DATA = [
    { id: 1, name: '1st Dept' },
    { id: 2, name: '2nd Dept' },
]

export const USERS_DATA = [
    {
        id: '1',
        image: 'https://source.unsplash.com/random/36x36',
        userName: 'john_doe',
        firstName: 'John',
        lastName: 'Doe',
        position: 'Design Engineer I',
        email: 'john.doe@example.com',
        businessUnit: '1st Dept',
        department: 'VSBU',
        created: '2024-03-25T00:00:00Z',
    },
    {
        id: '2',
        image: 'https://source.unsplash.com/random/36x36',
        userName: 'jane_smith',
        firstName: 'Jane',
        lastName: 'Smith',
        position: 'Design Engineer II',
        email: 'jane.smith@example.com',
        businessUnit: '2nd Dept',
        department: 'SSSBU',
        created: '2024-03-25T00:00:00Z',
    },
    {
        id: '3',
        image: 'https://source.unsplash.com/random/36x36',
        userName: 'mike_jones',
        firstName: 'Mike',
        lastName: 'Jones',
        position: 'Design Engineer III',
        email: 'mike.jones@example.com',
        businessUnit: '1st Dept',
        department: 'VSBU',
        created: '2024-03-25T00:00:00Z',
    },
    {
        id: '4',
        image: 'https://source.unsplash.com/random/36x36',
        userName: 'sarah_williams',
        firstName: 'Sarah',
        lastName: 'Williams',
        position: 'Design Engineer Trainee',
        email: 'sarah.williams@example.com',
        businessUnit: '2nd Dept',
        department: 'SSSBU',
        created: '2024-03-25T00:00:00Z',
    },
    {
        id: '5',
        image: 'https://source.unsplash.com/random/36x36',
        userName: 'david_brown',
        firstName: 'David',
        lastName: 'Brown',
        position: 'Design Engineer II',
        email: 'david.brown@example.com',
        businessUnit: '1st Dept',
        department: 'VSBU',
        created: '2024-03-25T00:00:00Z',
    },
    // Additional users
    {
        id: '6',
        image: 'https://source.unsplash.com/random/36x36',
        userName: 'emma_adams',
        firstName: 'Emma',
        lastName: 'Adams',
        position: 'Design Engineer Trainee',
        email: 'emma.adams@example.com',
        businessUnit: '2nd Dept',
        department: 'SSSBU',
        created: '2024-03-25T00:00:00Z',
    },
    {
        id: '7',
        image: 'https://source.unsplash.com/random/36x36',
        userName: 'matt_anderson',
        firstName: 'Matt',
        lastName: 'Anderson',
        position: 'Design Engineer I',
        email: 'matt.anderson@example.com',
        businessUnit: '1st Dept',
        department: 'VSBU',
        created: '2024-03-25T00:00:00Z',
    },
    {
        id: '8',
        image: 'https://source.unsplash.com/random/36x36',
        userName: 'olivia_smith',
        firstName: 'Olivia',
        lastName: 'Smith',
        position: 'Design Engineer III',
        email: 'olivia.smith@example.com',
        businessUnit: '1st Dept',
        department: 'VSBU',
        created: '2024-03-25T00:00:00Z',
    },
    {
        id: '9',
        image: 'https://source.unsplash.com/random/36x36',
        userName: 'michael_jackson',
        firstName: 'Michael',
        lastName: 'Jackson',
        position: 'Design Engineer II',
        email: 'michael.jackson@example.com',
        businessUnit: '2nd Dept',
        department: 'SSSBU',
        created: '2024-03-25T00:00:00Z',
    },
    {
        id: '10',
        image: 'https://source.unsplash.com/random/36x36',
        userName: 'amanda_miller',
        firstName: 'Amanda',
        lastName: 'Miller',
        position: 'Design Engineer III',
        email: 'amanda.miller@example.com',
        businessUnit: '1st Dept',
        department: 'VSBU',
        created: '2024-03-25T00:00:00Z',
    }
];

